### ISSUE TITLE
Could i play with someone not on my network if i port forward 12011 from my device?

### ISSUE THREAD

**Issue by fwuffyboi** [TMThong/Stardew-Mods#11]

**Comment by abdogm** [comment]
not really sure but you could try something like zerotier 
in theory is should work

**Comment by TMThong** [comment]
> not really sure but you could try something like zerotier in theory is should work

ZeroTier has support on all ports.  But I recommend NordVPN for more stable remote sharing with friends.

**Comment by fwuffyboi** [comment]
i tried it and the port forwarding worked for me. currently playing with friends, and the connection is quite stable.
