### ISSUE TITLE
Museum donation issue

### ISSUE THREAD

**Issue by WhiteWolf369** [TMThong/Stardew-Mods#13]
Hi! Thank you so much for creating such an incredible mod! 
Overall, it works really well! I've only encountered one issue in all the time I've been playing. Whenever I try to donate to the museum, it doesn't let me do anything (I'm not the host), it doesn't allow me to donate or close the window, and I have to exit the game. The host was able to donate once, but now every time she try, the same thing happens to her as it does to me.

I would greatly appreciate it if you could fix it! If not, no worries, it's still an awesome mod! Thanks!

**Comment by TMThong** [comment]
> Hi! Thank you so much for creating such an incredible mod! Overall, it works really well! I've only encountered one issue in all the time I've been playing. Whenever I try to donate to the museum, it doesn't let me do anything (I'm not the host), it doesn't allow me to donate or close the window, and I have to exit the game. The host was able to donate once, but now every time she try, the same thing happens to her as it does to me.
> 
> I would greatly appreciate it if you could fix it! If not, no worries, it's still an awesome mod! Thanks!

Yes but not now. Because I'm busy.

**Comment by WhiteWolf369** [comment]
I have been able to verify that this same problem occurs when you buy, for example, a stable or a goat. I believe, although I'm not certain yet, that it might be due to the controls I use. I use the last option, which is a joystick with two buttons, in case that information is helpful.

**Comment by Nhincaije** [comment]
> I have been able to verify that this same problem occurs when you buy, for example, a stable or a goat. I believe, although I'm not certain yet, that it might be due to the controls I use. I use the last option, which is a joystick with two buttons, in case that information is helpful.

This problem is smapi not mod

**Comment by TMThong** [comment]
Version 1.6 already has multiplayer functionality.
