### ISSUE TITLE
Bug, pls help

### ISSUE THREAD

**Issue by Jonh00979** [TMThong/Stardew-Mods#14]
Hi, I installed the mod and configured it correctly on smapi android version 1.4.5.128 but the coop button doesn't appear, can you help me? 
Log👇
![Screenshot_20231028_180952](https://github.com/TMThong/Stardew-Mods/assets/149272273/a0adabdd-0cad-43c7-bd8e-d76ce9976f5b)

**Comment by TMThong** [comment]
> Hi, I installed the mod and configured it correctly on smapi android version 1.4.5.128 but the coop button doesn't appear, can you help me? Log👇 ![Screenshot_20231028_180952](https://user-images.githubusercontent.com/149272273/278838116-a0adabdd-0cad-43c7-bd8e-d76ce9976f5b.jpg)

Please Install this mod in game version 1.4.5.39 or lasted

**Comment by TMThong** [comment]
> > Hi, I installed the mod and configured it correctly on smapi android version 1.4.5.128 but the coop button doesn't appear, can you help me? Log👇 ![Screenshot_20231028_180952](https://user-images.githubusercontent.com/149272273/278838116-a0adabdd-0cad-43c7-bd8e-d76ce9976f5b.jpg)
> 
> Please Install this mod in game version 1.4.5.39 or new version
