### ISSUE TITLE
Black Screen Coop

### ISSUE THREAD

**Issue by ShiroNy** [TMThong/Stardew-Mods#16]
When I'm playing coop, whenever we go to sleep, the screen goes completely black the next day, I use PC.

**Comment by TMThong** [comment]
@ShiroNy Please wait, I'll fix it when I'm free.

**Comment by TMThong** [comment]
@ShiroNy  Fixed.  [In this version!](https://github.com/TMThong/Stardew-Mods/releases/tag/multiplayer111)
