### ISSUE TITLE
no cabin bug

### ISSUE THREAD

**Issue by lildavegoth** [TMThong/Stardew-Mods#18]
when i and my gf go to sleep the screen keeps black and never end, and if my gf out by herself from the game or the game crashed and let her quit from the server itself. after she left, the game continue to showing selling popup. but after that, my gf cannot join to my world/server anymore, in my gf screen keeps showing warning **No available vabins**
![IMG-20240223-WA0023](https://github.com/TMThong/Stardew-Mods/assets/48707271/04976181-9d8a-407b-aed2-930d384dbbde)
im just playing with my gf, no one else

**Comment by TMThong** [comment]
> when i and my gf go to sleep the screen keeps black and never end, and if my gf out by herself from the game or the game crashed and let her quit from the server itself. after she left, the game continue to showing selling popup. but after that, my gf cannot join to my world/server anymore, in my gf screen keeps showing warning **No available vabins** ![IMG-20240223-WA0023](https://private-user-images.githubusercontent.com/48707271/307507122-04976181-9d8a-407b-aed2-930d384dbbde.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODA2NTMsIm5iZiI6MTcwODc4MDM1MywicGF0aCI6Ii80ODcwNzI3MS8zMDc1MDcxMjItMDQ5NzYxODEtOWQ4YS00MDdiLWFlZDItOTMwZDM4NGRiYmRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDEzMTIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYzQ1N2M2YTJmNDlkNDY1Y2M3ODU5YmY4NTk4MzdjZjZmZGI0OGZhYTQwNDlmMzhjYzlmMWU2MWIxYmU1YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0IQHmkQm7MxLAForHFGO_4uAA6Fy1Blm2DYp3p-oaaM) im just playing with my gf, no one else

@lildavegoth Can you give me version of mod and your log?

**Comment by lildavegoth** [comment]
sorry im doing a test on some mods that im using, and i found what make it bug.

this mod tool is the problem [Dynamic Game Assets](https://www.nexusmods.com/stardewvalley/mods/9365)

**Comment by lildavegoth** [comment]
here's the fix.
- when the black screen happens and never end all player must quit
- after their quit the game will continue to saving the data
- but, all players will no longer be able to join anymore

so, simply do this.
- destroy their cabins
- build another one
- tell them to join again (they will create a new account for the server)
- done

**Comment by lildavegoth** [comment]
here's the fix.
- when the black screen happens and never end all player must quit
- after their quit the game will continue to saving the data
- but, all players will no longer be able to join anymore

so, simply do this.
- destroy their cabins
- build another one
- tell them to join again (they will create a new account for the server)
- done

**Comment by TMThong** [comment]
> here's the fix.
> 
> * when the black screen happens and never end all player must quit
> * after their quit the game will continue to saving the data
> * but, all players will no longer be able to join anymore
> 
> so, simply do this.
> 
> * destroy their cabins
> * build another one
> * tell them to join again (they will create a new account for the server)
> * done

Ops! I think I should to try fix this error now.
