### ISSUE TITLE
Bug mission Adventurers' guild 

### ISSUE THREAD

**Issue by Felipevalley** [TMThong/Stardew-Mods#19]
When clicking on the card that says "If you defeat 10 slimes you will be able to join the adventurers guild When clicking on this card, the game completely crashes and when saving/sleeping it simply doesn't save. Please HELPPPPP

**Comment by TMThong** [comment]
Ok, I will fix it when I have free time.

**Comment by Felipevalley** [comment]
Example: we open the guild letter, when we go to harvest, our plants are floating, time stops for some, the worst thing is not being able to save them at the end of the day. It's been a week since my friends and I stopped playing, we're still sad today.

**Comment by TMThong** [comment]
> Example: we open the guild letter, when we go to harvest, our plants are floating, time stops for some, the worst thing is not being able to save them at the end of the day. It's been a week since my friends and I stopped playing, we're still sad today.

> I'm so sorry

**Comment by Felipevalley** [comment]
Don't worry! We know it's not easy to create a mod for mobile. On top of that, it makes you able to play together, we admire your work.

**Comment by CLeementine** [comment]
> Ok, I will fix it when I have free time.

have you fixed it?

**Comment by TMThong** [comment]
Version 1.6 already has multiplayer functionality.
