### ISSUE TITLE
Black screen Bug

### ISSUE THREAD

**Issue by YusufSametgkc** [TMThong/Stardew-Mods#22]
Man There's a Problem of my multiplayer mod.... I joined my friends world then i sell things at the selling bin then when i press the check button and shows the day of the game it simply wont continue..

But it saves the game file

**Comment by TMThong** [comment]
Which Mod version are you using? @YusufSametgkc

**Comment by Isaacluvsb** [comment]
It happens to me as well, im on 1.1.2v

**Comment by TMThong** [comment]
Version 1.6 already has multiplayer functionality.
