### ISSUE TITLE
Multiplayer Mod Smapi v.3.18.3.1

### ISSUE THREAD

**Issue by Mica0700** [TMThong/Stardew-Mods#24]
Hello, I use **Smapi v.3.18.3.1**, I installed the multiplayer mod, the latest version, but when I play in multiplayer the server crashes within minutes. And in the console I get a warning about this same mod. Is there any solution?

**Comment by TMThong** [comment]
@Mica0700 Can you give me your log.

**Comment by Mica0700** [comment]
![Screenshot_20240726-153713](https://github.com/user-attachments/assets/9c3cf71e-9cd9-4bd9-aa4c-2d80d8bba3fb)

**Comment by TMThong** [comment]
@Mica0700 When does this error usually appear?
