### ISSUE TITLE
Bug of version 1.0.8

### ISSUE THREAD

**Issue by TMThong** [TMThong/Stardew-Mods#3]

**Comment by HORRORVI** [comment]
> > Sau khi cập nhật thì mình không thể join vào map của bạn ở xa mặc dù đã dùng ZeroTier One(bản 1.0.3 thì được). Bạn khác dùng Pc thì lại vào được map mobile.
> 
> Bản 1.0.5 mình mới ra , bạn xem thử nhé

Bản này Vào map bị đơ, không load được và bị văng game

**Comment by HORRORVI** [comment]
New map thì vào được nhưng lần sau vào lại bị đơ

**Comment by TMThong** [comment]
> New map thì vào được nhưng lần sau vào lại bị đơ

Ok để mình test cái

**Comment by TMThong** [comment]
@HORRORVI  bản mới fix r nhé

**Comment by Nhincaije** [comment]
> @HORRORVI  bản mới fix r nhé

Bản 1.0.6 co-op chung mạng hoạt tốt nhưng ko thể co-op xa được nữa:"(

**Comment by HORRORVI** [comment]
> > @HORRORVI  bản mới fix r nhé
> 
> Bản 1.0.6 co-op chung mạng hoạt tốt nhưng ko thể co-op xa được nữa:"(

Mình chơi bình thường nhé bạn, coi lại IP nhé

**Comment by Nhincaije** [comment]
> > > @HORRORVI  bản mới fix r nhé
> > 
> > Bản 1.0.6 co-op chung mạng hoạt tốt nhưng ko thể co-op xa được nữa:"(
> 
> Mình chơi bình thường nhé bạn, coi lại IP nhé

Có vẻ là như thế nhưng chắc mai thử lại

**Comment by Nhincaije** [comment]
> new version supported VPN @bagheri76 @HORRORVI 

Thank you for your efforts 🥰

**Comment by HORRORVI** [comment]
Lỗi 1.0.6, bị đơ khi tặng đồ cho người chơi khác

**Comment by TMThong** [comment]
> Lỗi 1.0.6, bị đơ khi tặng đồ cho người chơi khác

Ném log đi bạn, nếu không có thì nào rảnh mình fix. Chứ giờ phải kiếm tí tiền ăn

**Comment by Nhincaije** [comment]
> Lỗi 1.0.6, bị đơ khi tặng đồ cho người chơi khác

Bạn nên ném log để có thể đc fix sớm nhất

**Comment by HORRORVI** [comment]
> > Lỗi 1.0.6, bị đơ khi tặng đồ cho người chơi khác
> 
> Ném log đi bạn, nếu không có thì nào rảnh mình fix. Chứ giờ phải kiếm tí tiền ăn

Um, để mình test lại xong gửi log cho bạn

**Comment by bagheri76** [comment]
I play it till day 16 and everything works perfect if see any errors i will tell you.😍🔥

**Comment by howiejr2000** [comment]
How to I get the IP for I server I created

**Comment by Nhincaije** [comment]
> How to I get the IP for I server I created 

![Screenshot_2023-05-12-11-43-14-39_9fd108bf25e5d856ac914678a7976b37.jpg](https://github.com/TMThong/Stardew-Mods/assets/88138360/c5aef576-2f5c-4c53-bd35-334ddd16d794)

It is here

**Comment by howiejr2000** [comment]
I think I did something wrong because I don't see that

**Comment by bagheri76** [comment]
I don't know it's because of game or mod but in mine and touch mod and auto attack second player stuck and can't move and after give gift to that player it can move.

**Comment by TMThong** [comment]
> I don't know it's because of game or mod but in mine and touch mod and auto attack second player stuck and can't move and after give gift to that player it can move.

I've been reported about this error but I won't be able to fix it right away because I'm busy making some money to pay for the network.

**Comment by TMThong** [comment]
> I don't know it's because of game or mod but in mine and touch mod and auto attack second player stuck and can't move and after give gift to that player it can move.

I just did a quick test on my hands free but it's a function of the game.

**Comment by howiejr2000** [comment]
I'm having a problem I think I did something wrong I can't find the IP address

**Comment by TMThong** [comment]
> Tôi đang gặp sự cố, tôi nghĩ rằng tôi đã làm gì đó sai, tôi không thể tìm thấy địa chỉ IP

1.You need to download NordVPN on the CHPlay store or for your computer, download it on the NordVPN homepage.
2.You need to create an account or log in with Google, Facebook ...
3.So that when you log in you select the Meshnet tab and turn it on, you need to remember the ip address after turning it on, because if you are a host you need to give this address to a partner.
4.You need to send an invitation to the partner via email address and the partner approves it, then you can play 1 normal way.

Try this VPN, you watch my new video on youtube for more clarity.

**Comment by AgChax123** [comment]
Anh ơi. Lỗi hiến đồ cho ông gunner ko đc,  ấn dấu x bên góc phải trên cùng nó cũng ko cho thoát 
![Uploading received_570437618561144.jpeg…]()

**Comment by Nhincaije** [comment]
> Anh ơi. Lỗi hiến đồ cho ông gunner ko đc,  ấn dấu x bên góc phải trên cùng nó cũng ko cho thoát 
> ![Uploading received_570437618561144.jpeg…]()
> 

Ném log đi ôg điều đó giúp fix nhanh dễ dàng hơn

**Comment by AgChax123** [comment]
> hơn

Tui tưởng ôg cũng phải bị lỗi này chứ nhỉ?

**Comment by Nhincaije** [comment]
> > hơn
> 
> Tui tưởng ôg cũng phải bị lỗi này chứ nhỉ?

Nope._.

**Comment by TMThong** [comment]
> > hơn
> 
> Tui tưởng ôg cũng phải bị lỗi này chứ nhỉ?

Mình không có test hết bạn ạ, với mình chưa rảnh tay còn đi kiếm tí tiền sinh hoạt bạn

**Comment by Nhincaije** [comment]
> > > hơn
> > 
> > Tui tưởng ôg cũng phải bị lỗi này chứ nhỉ?
> 
> Mình không có test hết bạn ạ, với mình chưa rảnh tay còn đi kiếm tí tiền sinh hoạt bạn

Tôi có gửi log về lỗi bảo tàng rồi ông xem nào rãnh tay rồi fix

**Comment by 1523006317** [comment]
This is a recorded video of the problem occurring. This bug has significantly affected multiplayer games and we hope to find a solution😅

**Comment by 1523006317** [comment]
> This is a recorded video of the problem occurring. This bug has significantly affected multiplayer games and we hope to find a solution😅

【超级会员V3】通过百度网盘分享的文件：Screenre…
链接:https://pan.baidu.com/s/1s4hqaSK_px9RCXy99lJBnw 
提取码:qcg4
复制这段内容打开「百度网盘APP 即可获取」

**Comment by TMThong** [comment]
> > This is a recorded video of the problem occurring. This bug has significantly affected multiplayer games and we hope to find a solution😅
> 
> 【超级会员V3】通过百度网盘分享的文件：Screenre… 链接:[https://pan.baidu.com/s/1s4hqaSK_px9RCXy99lJBnw ](https://pan.baidu.com/s/1s4hqaSK_px9RCXy99lJBnw%C2%A0) 提取码:qcg4 复制这段内容打开「百度网盘APP 即可获取」

I'm so sorry but I don't know chinese, mind you uploading videos to international platforms, thank you.

**Comment by TMThong** [comment]
> > This is a recorded video of the problem occurring. This bug has significantly affected multiplayer games and we hope to find a solution😅
> 
> 【超级会员V3】通过百度网盘分享的文件：Screenre… 链接:[https://pan.baidu.com/s/1s4hqaSK_px9RCXy99lJBnw ](https://pan.baidu.com/s/1s4hqaSK_px9RCXy99lJBnw%C2%A0) 提取码:qcg4 复制这段内容打开「百度网盘APP 即可获取」

I'm sorry it seems that the web you uploaded the file won't let me download, I suspect due to china's firewall policies.

**Comment by 1523006317** [comment]
I'm sorry, I am now trying to share the file using Google Drive. Here is the link:    https://drive.google.com/file/d/1-70MjsVfymTBCQHrcXJCQmZoIgPlEcW5/view?usp=drivesdk

**Comment by bagheri76** [comment]
> I'm sorry, I am now trying to share the file using Google Drive. Here is the link: https://drive.google.com/file/d/1-70MjsVfymTBCQHrcXJCQmZoIgPlEcW5/view?usp=drivesdk

Give access to all

**Comment by TMThong** [comment]
> I'm sorry, I am now trying to share the file using Google Drive. Here is the link: https://drive.google.com/file/d/1-70MjsVfymTBCQHrcXJCQmZoIgPlEcW5/view?usp=drivesdk

I just need you to upload the log to https://smapi.io/log and send the log link.  There's no need for that kind of trouble.

**Comment by 1523006317** [comment]
> I don't know what happened, the interface suddenly got stuck. Except for the inventory and virtual keyboard, nothing else responds when clicked. This is my game log:  https://smapi.io/log/5813bdfcae424caf8b85b2db09c18055

@TMThong Sure, the game log has been uploaded.😅

**Comment by TMThong** [comment]
@Nhincaije @howiejr2000 @bagheri76 @1523006317 new version

**Comment by 1523006317** [comment]
> @Nhincaije @howiejr2000 @bagheri76 @1523006317 new version

I found that the new version seems to have not fixed the previous two bugs, which are the problem of not being able to exit and the issue of the trash can icon in multiplayer games not being able to delete saved files still exist.😅

**Comment by 1523006317** [comment]
> > @Nhincaije @howiejr2000 @bagheri76 @1523006317 new version
> 
> I found that the new version seems to have not fixed the previous two bugs, which are the problem of not being able to exit and the issue of the trash can icon in multiplayer games not being able to delete saved files still exist.😅

![IMG_20230515_132119.jpg](https://github.com/TMThong/Stardew-Mods/assets/132871179/2bfe15a6-645b-4401-8220-fc40e0216781)

![IMG_20230515_132202.jpg](https://github.com/TMThong/Stardew-Mods/assets/132871179/20c0dd54-f616-43b2-9b05-33dce7b9d297)

**Comment by TMThong** [comment]
> > @Nhincaije @howiejr2000 @bagheri76 @1523006317 new version
> 
> I found that the new version seems to have not fixed the previous two bugs, which are the problem of not being able to exit and the issue of the trash can icon in multiplayer games not being able to delete saved files still exist.😅

Sorry but I don't have enough time to fix it all.

**Comment by 1523006317** [comment]
Has the bug that caused players to get stuck and unable to move or access the menu settings been fixed in version 1.08?

**Comment by 1523006317** [comment]
> Has the bug that caused players to get stuck and unable to move or access the menu settings been fixed in version 1.08?

I have already set the link to be accessible to everyone，The bug displayed in the video in this link:   https://drive.google.com/file/d/1-70MjsVfymTBCQHrcXJCQmZoIgPlEcW5/view?usp=drivesdk

**Comment by bagheri76** [comment]
> @Nhincaije @howiejr2000 @bagheri76 @1523006317 new version

Thanks 🔥😍💯

**Comment by TMThong** [comment]
> > Has the bug that caused players to get stuck and unable to move or access the menu settings been fixed in version 1.08?
> 
> I have already set the link to be accessible to everyone，The bug displayed in the video in this link: https://drive.google.com/file/d/1-70MjsVfymTBCQHrcXJCQmZoIgPlEcW5/view?usp=drivesdk

In my opinion this error occurs when it is too late and you are assigned the immobilized attribute.

**Comment by 1523006317** [comment]
> > > @Nhincaije @howiejr2000 @bagheri76 @1523006317 new version
> > 
> > I found that the new version seems to have not fixed the previous two bugs, which are the problem of not being able to exit and the issue of the trash can icon in multiplayer games not being able to delete saved files still exist.😅
> 
> Sorry but I don't have enough time to fix it all.

Okay, we will wait patiently for you whenever you have free time because the Android version on that page only has an exit button. Otherwise, we can only switch to the background and close it to exit. If the exit function works properly, that would be great. 🌷

**Comment by Nhincaije** [comment]
> @Nhincaije @howiejr2000 @bagheri76 @1523006317 new version

Thank you for your efforts ️

**Comment by Nhincaije** [comment]
> @Nhincaije @howiejr2000 @bagheri76 @1523006317 new version

Thank you for your efforts ️

**Comment by Nhincaije** [comment]
Hmm có vẻ nó vẫn bị lỗi khi hiến cổ vật cho bảo tàng

**Comment by AgChax123** [comment]
> Hmm có vẻ như nó vẫn bị lỗi khi trưng bày cổ vật cho bảo tàng

Này tui nghĩ do smapi ấy. Gỡ mod nó vẫn bị :)

**Comment by Nhincaije** [comment]
> > Hmm có vẻ như nó vẫn bị lỗi khi trưng bày cổ vật cho bảo tàng
> 
> Này tui nghĩ do smapi ấy. Gỡ mod nó vẫn bị :)

Chuẩn luôn rồi:)), tôi test cả hai bản 1 bản của crack 1 bản của bản quyền vẫn bị

**Comment by TMThong** [comment]
> > > Hmm có vẻ như nó vẫn bị lỗi khi trưng bày cổ vật cho bảo tàng
> > 
> > 
> > Này tui nghĩ do smapi ấy. Gỡ mod nó vẫn bị :)
> 
> Chuẩn luôn rồi:)), tôi test cả hai bản 1 bản của crack 1 bản của bản quyền vẫn bị

Má biết tiếng việt thì nói đi ghi tiếng anh chi z :))

**Comment by 1523006317** [comment]
> 

@TMThong   We have encountered this situation many times. It could happen at any time and any place. Can this bug be resolved?🤔

**Comment by TMThong** [comment]
> We have encountered this situation many times. It could happen at any time and any place. Can this bug be resolved?

I don't know, but I fixed it in the log you reported. Except for 1 number of errors I am not free to consider.

**Comment by Nhincaije** [comment]
> > > > Hmm có vẻ như nó vẫn bị lỗi khi trưng bày cổ vật cho bảo tàng
> > > 
> > > 
> > > Này tui nghĩ do smapi ấy. Gỡ mod nó vẫn bị :)
> > 
> > Chuẩn luôn rồi:)), tôi test cả hai bản 1 bản của crack 1 bản của bản quyền vẫn bị
> 
> Má biết tiếng việt thì nói đi ghi tiếng anh chi z :))

Cho nó ngầu:)))))

**Comment by bagheri76** [comment]
@TMThong hi dev in the new version 1.0.9 these button are not working
![IMG_20230518_214748](https://github.com/TMThong/Stardew-Mods/assets/126345257/05d86726-3356-4a4f-ade7-2e055a21b9f4)

**Comment by 1523006317** [comment]
@TMThong   Hello, great MOD author. I would like to know if you can fix the issue that the exit button is still not working on Android. When I click on it, the screen turns black and does not exit to the desktop.☺️
![IMG_20230521_024516](https://github.com/TMThong/Stardew-Mods/assets/132871179/a8f9895a-fe65-49f3-8906-d1ed93691686)
![Screenshot_2023-05-21-02-39-21-891_com zane stardewvalley](https://github.com/TMThong/Stardew-Mods/assets/132871179/fe2104f0-d05f-4825-9adb-728948081f82)

**Comment by Nhincaije** [comment]
Hmmm lỗi hiến cổ vật cho bảo tàng, xây dựng công trình, di chuyển công trình còn không anh

**Comment by AgChax123** [comment]
> Hmmm lỗi hiến cổ vật cho bảo tàng, xây dựng công trình, di chuyển công trình còn không anh

Lỗi hiến cổ vật bảo tàng là do smapi bạn ơi. Ko phải do mod đâu. Này đã nói ở trên r mà :))

**Comment by AgChax123** [comment]
Đơn là bạn tải bản smapi về. Để đó chưa mod gì cả rồi vô chs nó cũng bị. Suy ra ko phải lỗi do mod.

**Comment by TMThong** [comment]
> > > Hmmm lỗi hiến cổ vật cho bảo tàng, xây dựng công trình, di chuyển công trình còn không anh
> > 
> > 
> > Lỗi hiến cổ vật bảo tàng là do smapi bạn ơi. Ko phải do mod đâu. Này đã nói ở trên r mà :))
> 
> Trc có nói về lỗi nhưng nhận ra lỗi do smapi ko phải mod, nhưng Thông lại nói là do mod chưa hỗ trợ hay tuơng tự gì đó nên giờ hỏi lại cho chắc coi lỗi do đâu;-;

Tôi bảo nào rảnh vá cả SMAPI để fix thôi

**Comment by AgChax123** [comment]
> > > > Hừm, lỗi phế liệu cổ vật cho bảo tàng, xây dựng công trình, di chuyển công trình còn không anh
> > > 
> > > 
> > > Lỗi hiển thị cổ vật bảo tàng là do smapi bạn ơi. Ko phải làm mod đâu. Điều này đã nói ở trên r mà :))
> > 
> > 
> > Trc có nói về lỗi nhưng nhận ra lỗi do smapi không phải mod, nhưng Thông báo lại nói là do mod không hỗ trợ hay tương tự gì đó nên giờ hỏi lại cho chắc lỗi ở đâu ;-;
> 
> Tôi bảo đảm bất kỳ khoảng trống nào vá cả SMAPI để sửa thôi

,

> > > > Hừm, lỗi trả vật liệu cổ vật cho bảo tàng, xây dựng công trình, di chuyển công trình còn không anh
> > > 
> > > 
> > > Lỗi hiển thị cổ vật bảo tàng là do smapi bạn ơi. Ko phải làm mod đâu. Điều này đã nói ở trên mà :))
> > 
> > 
> > Trc có nói về lỗi nhưng nhận ra lỗi do smapi không phải mod, nhưng Thông báo lại nói là do mod không hỗ trợ hay tương tự như vậy nên giờ hỏi lại xem có chắc lỗi ở đâu không ;-;
> 
> Tôi đảm bảo bất kỳ khoảng trống nào vá cả SMAPI để sửa đổi

Smapi tôi nghĩ chờ bên phía người tạo ra họ fix. Vì đây cũng là bản chưa hoàn chỉnh nên lỗi cũng đúng

**Comment by HORRORVI** [comment]
> Hmmm lỗi hiến cổ vật cho bảo tàng, xây dựng công trình, di chuyển công trình còn không anh

Lỗi này là lỗi ở game gốc khi chơi nút ảo sẽ bị, bạn tắt nút ảo, dùng chạm để di chuyển là oke nhé

**Comment by Nhincaije** [comment]
> > Hmmm lỗi hiến cổ vật cho bảo tàng, xây dựng công trình, di chuyển công trình còn không anh
> 
> Lỗi này là lỗi ở game gốc khi chơi nút ảo sẽ bị, bạn tắt nút ảo, dùng chạm để di chuyển là oke nhé

Lỗi này không phải ở game gốc mà lỗi ở phần mềm smapi, tôi đã thử trên smapi đúng như bạn nói chỉ cần chuyển qua chạm để di chuyển thì ko bị đơ nữa nhưng đối với game (bản quyền) khi tôi dùng nút ảo và thử mua vật tư hay cống hiến thì nó vẫn hoạt động bình thường
