### ISSUE TITLE
Compatibility with stardew valley on PC?

### ISSUE THREAD

**Issue by gingercookies** [TMThong/Stardew-Mods#5]
Hi, when i play SV on PC with a friend of mine who plays on mobile with this mod installed.
When we go to bed and end a day, we hit the black-screen thing. It prevent us from continue the game and force to restart the game to be able to play again. 
This happen when my PC being the host (both smapi and normal SV), my friends being the client or PC is the client and mobile is the host.

**Comment by Nhincaije** [comment]
> Hi, when i play SV on PC with a friend of mine who plays on mobile with this mod installed.
> When we go to bed and end a day, we hit the black-screen thing. It prevent us from continue the game and force to restart the game to be able to play again. 
> This happen when my PC being the host (both smapi and normal SV), my friends being the client or PC is the client and mobile is the host. 

I have a temporary fix you can try, before you sleep through the day, put an item in the "shipping" box so that when you sleep through the day you will not have the black screen error again.

**Comment by Nhincaije** [comment]
> Hi, when i play SV on PC with a friend of mine who plays on mobile with this mod installed.
> When we go to bed and end a day, we hit the black-screen thing. It prevent us from continue the game and force to restart the game to be able to play again. 
> This happen when my PC being the host (both smapi and normal SV), my friends being the client or PC is the client and mobile is the host. 

Note that all participants in the host, including the host, must sell and sell anything as long as they sleep through the day, and the statistics of money earned during the day appear.

**Comment by gingercookies** [comment]
> put an item in the "shipping" box so that when you sleep through the day you will not have the black screen error again.

I tried it with my friend phone being the host and my PC being the host.
Nothing works, i still got the dark screen
I will attached my logs when my friend phone hosting
[SMAPI-latest.txt](https://github.com/TMThong/Stardew-Mods/files/11832721/SMAPI-latest.txt)

**Comment by Nhincaije** [comment]
> > put an item in the "shipping" box so that when you sleep through the day you will not have the black screen error again.
> 
> I tried it with my friend phone being the host and my PC being the host.
> Nothing works, i still got the dark screen
> I will attached my logs when my friend phone hosting
> [SMAPI-latest.txt](https://github.com/TMThong/Stardew-Mods/files/11832721/SMAPI-latest.txt)
> 
> Edit: The "Disconnected: ClosedGame" just me alt+f4 the game

Are you sure all the players are selling items using the loot box

**Comment by Nhincaije** [comment]
> > put an item in the "shipping" box so that when you sleep through the day you will not have the black screen error again.
> 
> I tried it with my friend phone being the host and my PC being the host.
> Nothing works, i still got the dark screen
> I will attached my logs when my friend phone hosting
> [SMAPI-latest.txt](https://github.com/TMThong/Stardew-Mods/files/11832721/SMAPI-latest.txt)
> 
> Edit: The "Disconnected: ClosedGame" just me alt+f4 the game

Are you sure all the players are selling items using the loot box

**Comment by gingercookies** [comment]
Yes.
The only time this won't happen is when we didn't sell anything, just sleep

**Comment by Nhincaije** [comment]
> Yes.
> The only time this won't happen is when we didn't sell anything, just sleep

How and where do you sell it?

**Comment by gingercookies** [comment]
> How and where do you sell it?

Just axed a tree then take one log, put it in the shipping bin

**Comment by Nhincaije** [comment]
> > How and where do you sell it?
> 
> Just axed a tree then take one log, put it in the shipping bin
> 

Tất cả người chơi đều làm điều đó đúng chứ

**Comment by Nhincaije** [comment]
> > How and where do you sell it?
> 
> Just axed a tree then take one log, put it in the shipping bin
> 

Everyone is selling, right

**Comment by gingercookies** [comment]
> > > How and where do you sell it?
> > 
> > 
> > Just axed a tree then take one log, put it in the shipping bin
> 
> Everyone is selling, right

Yes

**Comment by Nhincaije** [comment]
> > > > How and where do you sell it?
> > > 
> > > 
> > > Just axed a tree then take one log, put it in the shipping bin
> > 
> > Everyone is selling, right
> 
> Yes

Looks like it's not useless when playing on different platforms

**Comment by TMThong** [comment]
@gingercookies  Fixed.  [In this version!](https://github.com/TMThong/Stardew-Mods/releases/tag/multiplayer111)
