### ISSUE TITLE
Not working under version 1.5.6.39

### ISSUE THREAD

**Issue by XiaolanX** [TMThong/Stardew-Mods#6]
![Screenshot_2023-06-25-22-38-17-278_com zane stard](https://github.com/TMThong/Stardew-Mods/assets/67143380/e01ea8ee-1b6f-4ac7-adc4-9b7cf903d3e2)
![Screenshot_2023-06-26-16-40-19-693_com zane stard](https://github.com/TMThong/Stardew-Mods/assets/67143380/1cc16295-0329-45c8-9f55-55c29aa5884a)
Just like in the picture, they don't display the buttons for multiplayer 
(From mechanical translation)

**Comment by XiaolanX** [comment]
The mod version is the latest 1.1.0

**Comment by TMThong** [comment]
> The mod version is the latest 1.1.0

@XiaolanX Pls, give me your log.

**Comment by bagheri76** [comment]
> > ![Screenshot_2023-06-25-22-38-17-278_com zane stard](https://user-images.githubusercontent.com/67143380/248734341-e01ea8ee-1b6f-4ac7-adc4-9b7cf903d3e2.jpg) ![Screenshot_2023-06-26-16-40-19-693_com zane stard](https://user-images.githubusercontent.com/67143380/248734611-1cc16295-0329-45c8-9f55-55c29aa5884a.jpg) Just like in the picture, they don't display the buttons for multiplayer (From mechanical translation)
> 
> dude you use old multiplayer mod

![Uploading Screenshot_2023-06-26-13-05-38-260_com.android.chrome-edit.jpg…]()

**Comment by bagheri76** [comment]
> The mod version is the latest 1.1.0

![Screenshot_2023-06-26-13-05-38-260_com android chrome-edit](https://github.com/TMThong/Stardew-Mods/assets/126345257/548a0dd0-9134-4731-a26d-c02a2ff6cca9)
