### ISSUE TITLE
About on Android multiplayer games sometimes get stuck and inactive

### ISSUE THREAD

**Issue by 1523006317** [TMThong/Stardew-Mods#7]
I wonder if you've ever been stuck and unable to move while digging or cutting down trees? We often come across situations where we can only get a friend to give us a gift, it can be troublesome if your teammate is not around, and it takes a certain amount of time for your friend to arrive. Can this bug be fixed by the author? Because it affects everyone's gaming experience very much.

**Comment by 1523006317** [comment]
It doesn't matter the time and place, the player character sometimes gets stuck inexplicably, can't move, can't click anything, can only click on the items in the inventory, and the settings can't be opened

**Comment by bagheri76** [comment]
> It doesn't matter the time and place, the player character sometimes gets stuck inexplicably, can't move, can't click anything, can only click on the items in the inventory, and the settings can't be opened

yes it's happen when you break stones and chop trees most of the time.but you can change your controller settings to joystick and buttons when you break stones or .... and there will be no stuck.
![Screenshot_2023-06-27-00-51-44-674_com zane stardewvalley](https://github.com/TMThong/Stardew-Mods/assets/126345257/2875cf7f-afd9-4de5-80f2-41ee668c2e74)

**Comment by Nhincaije** [comment]
I have installed a mod called "What are you missing" and have to use F2 button to pop up the mod's menu, so every time I get stuck just press F2 button with virtual keyboard the mod menu pops up and I'm not stuck, It's really great because every time I go mining I don't have to worry about getting stuck

**Comment by I3elphegor** [comment]
You can also type in the console: debug canmove
But other solutions seems faster.

**Comment by FurmigaHumana** [comment]
This is basicaly the only bug I encountered, I am the host and I can't go to the mine with the other player because as soon as I start breaking rocks he will be unable to move, "debug canmove" works but sometimes it will get stuck while being attacked and die.
