### ISSUE TITLE
Ada bug seperti ini saat saya memulai festival egg di mode multipemain

### ISSUE THREAD

**Issue by angga2a** [TMThong/Stardew-Mods#9]
![Screenshot_20230715_085020](https://github.com/TMThong/Stardew-Mods/assets/139602862/69268252-b1f0-4343-917c-019240a03b86)

**Comment by TMThong** [comment]
I suspect this happens at most events when it's too dark. You can check it for me and please give me a log so I can correct it at the earliest.

**Comment by angga2a** [comment]
Mohon maaf bug ini terjadi karena saya memasang mod bahasa indonesia, saat
saya menghapus mod bahasa indonesia, mod ini berjalan lancar,

Tetapi Masih ada satu bug dimana saat pemain tidur pemain yang menjual
barang mereka terbangun seperti biasa, Tetapi saat pemain lain yang tidak
menjual barang sebelum meraka tidur
Tidak dapat terbangun dari tidur mereka layar hitam tidak bisa di sentuh.

Pada tanggal Sab, 15 Jul 2023 14:55, Trần Minh Thông <
***@***.***> menulis:
